### ISSUE TITLE
Why `try_split` can only be called once?

### ISSUE THREAD

**Issue by Dirreke** [ethercrab-rs/ethercrab#182]
I use ethercrab as a part of my program. And I have to reset the program in some reason.
However, for `ethercrab`, I get an error when call [try_split](https://github.com/ethercrab-rs/ethercrab/blob/e3e2e9cda447a5e5a128b77c5d02f19b25a4f28b/src/pdu_loop/storage.rs#L86-L105). Then, I tried to make PduRx, PduTx.... be a static variable and I'm failed, either

I'm not familiar with the underlying logic. However, I want to know if we can use `once` to make sure we only call `compare_exchange` once and then every time I call try_split, it will return (rx, tx, pduloop).
Alternatively, I want to know if we can split the `try_split` into two parts, one for calling `compare_exchange` and the other for returning the `(rx, tx, pdu_loop)`. In this way, I can use the former method to get the  `(rx, tx, pdu_loop)` and run the task.

Thanks!

**Comment by jamwaffles** [comment]
`try_split` is designed in such a way to uphold the invariant that only one `PduTx` and `PduRx` may be held at a time, otherwise there's the potential for race conditions and other UB if more than one of either of these instances is held concurrently.

Are you able to put the part of your program that needs to be reset in a `loop`? That way you can reset as much as you like on failure but only need to call `try_split` once. 

It would be good if you could describe what you mean by "reset the program" in a bit more detail. Are you encountering NIC issues, program bugs, etc? Does your program crash a thread as opposed to returning a `Result::Err(...)`, etc?

**Comment by jamwaffles** [comment]
If this suits your application, you could use `thread::scope` which allows `PduStorage` to be non-`'static`. Here's a demo that uses `smol::block_on` which executes futures on two threads; one the TX/RX, the other the actual task thread: 

```rust
use env_logger::Env;
use ethercrab::{
    error::Error,
    std::{tx_rx_task},
    Client, ClientConfig, PduStorage, Timeouts,
};
use futures_lite::StreamExt;
use std::{thread, time::Duration};

/// Maximum number of slaves that can be stored. This must be a power of 2 greater than 1.
const MAX_SLAVES: usize = 16;
/// Maximum PDU data payload size - set this to the max PDI size or higher.
const MAX_PDU_DATA: usize = 1100;
/// Maximum number of EtherCAT frames that can be in flight at any one time.
const MAX_FRAMES: usize = 16;
/// Maximum total PDI length.
const PDI_LEN: usize = 64;

fn main() -> Result<(), Error> {
    env_logger::Builder::from_env(Env::default().default_filter_or("info")).init();

    let interface = std::env::args()
        .nth(1)
        .expect("Provide network interface as first argument.");

    let pdu_storage: PduStorage<MAX_FRAMES, MAX_PDU_DATA> = PduStorage::new();

    let (tx, rx, pdu_loop) = pdu_storage.try_split().expect("can only split once");

    let client = Client::new(pdu_loop, Timeouts::default(), ClientConfig::default());

    thread::scope(|s| {
        // TODO: Handle panics!
        let _tx_rx_task =
            s.spawn(|| smol::block_on(tx_rx_task(&interface, tx, rx).expect("spawn TX/RX task")));

        let app_task = s.spawn(|| {
            smol::block_on(async {
                let mut group = client
                    .init_single_group::<MAX_SLAVES, PDI_LEN>()
                    .await
                    .expect("Init")
                    .into_op(&client)
                    .await
                    .expect("PRE-OP -> OP");

                let mut tick_interval = smol::Timer::interval(Duration::from_millis(5));

                loop {
                    group.tx_rx(&client).await.expect("TX/RX");

                    // Cyclic data sent here
                    for mut slave in group.iter(&client) {
                        let (_i, o) = slave.io_raw_mut();

                        for byte in o.iter_mut() {
                            *byte = byte.wrapping_add(1);
                        }
                    }

                    tick_interval.next().await;
                }
            })
        });

        app_task.join().unwrap()
    })
}
```

If you don't want to use threads, this should also work on an executor that doesn't require `'static` bounds on futures passed to it, for example [`smol::LocalExecutor`](https://docs.rs/smol/latest/smol/struct.LocalExecutor.html#method.spawn).

There might be other options but I'd need to see your code to tell for sure. I'm available for contracting hours if you have appetite for that.

**Comment by jamwaffles** [comment]
Ah, right, sorry about that! I fixed it a while ago for Linux/UNIX but I don't test on Windows any more so that slipped past.

I've opened #183 to fix. I'm going to test it now but if you want to, try changing your `Cargo.toml` to:

```toml
ethercrab = { git = "https://github.com/ethercrab-rs/ethercrab.git", branch = "non-static-windows" }
```
