### ISSUE TITLE
EEPROM strings contain trailing null bytes

### ISSUE THREAD

**Issue by jamwaffles** [ethercrab-rs/ethercrab#22]
Issue #21 raised a bug where strings read from the slave device contain trailing null bytes (`\0`). These should be trimmed from the returned string, otherwise we get behaviour like a slave name of `"R88D-1SN04H-ECT\0\0\0\0\0"`.

Presumably this slave device assumes a language with null-terminated strings is reading the EEPROM, so is a bit loose about what it returns after the string data. In this specific case, the slave device reports a length of 20 bytes for the string, where `"R88D-1SN04H-ECT"` is only 15 bytes long.

**Comment by jimy-byerley** [comment]
So this was an issue with the servodrive's firmware, interesting :thinking:

**Comment by jimy-byerley** [comment]
I would guess the same, but since the ethercat specs do not mention the names should be read as null-terminated strings, I find Omron tricky to rely on it ;)

**Comment by jamwaffles** [comment]
No, even better, EtherCAT SII strings have a length field just before them so really there's no excuse 😁 but this is where the real world meets EtherCrab, and the realworld up till now has been mostly C :(
