### ISSUE TITLE
Does EK1100 stay in OP?

### ISSUE THREAD

**Issue by jamwaffles** [ethercrab-rs/ethercrab#61]
Since the beginning, my EK1100's `Run` light has blinked during what I thought was `OP`, however the [spec sheet](https://download.beckhoff.com/download/Document/io/ethercat-terminals/ek110x_ek15xxen.pdf) says:

![image](https://github.com/ethercrab-rs/ethercrab/assets/800791/33e300a1-ee6e-4e3d-9bd6-bde0cc033b61)

Which seems to imply it is in SAFE-OP. Maybe it enters OP, EtherCrab is happy, then it falls back out of OP. This needs looking into.

**Comment by fpdotmonkey** [comment]
Launching the `ek1100` demo with a EK1100-EL4132-EL3104 setup yields the whole system running in SAFEOP.  I've attached logs and a wireshark capture of a debug run on commit 4590fe8 with the attached patch applied (for Windows and EL3104 compatibility)

[ethercrab-no-op-20230705T1324Z.zip](https://github.com/ethercrab-rs/ethercrab/files/11958387/ethercrab-no-op-20230705T1324Z.zip)
